import "dotenv/config";

export const Config = {
	DATABASE_URL: process.env.DATABASE_URL || "",
	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || "",
	GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || "",
	GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID || "",
	GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET || "",
	NEXT_PUBLIC_STREAM_VIDEO_API_KEY:
		process.env.NEXT_PUBLIC_STREAM_VIDEO_API_KEY || "",
	STREAM_VIDEO_API_SECRET: process.env.STREAM_VIDEO_API_SECRET || "",
	NEXT_PUBLIC_STREAM_CHAT_API_KEY:
		process.env.NEXT_PUBLIC_STREAM_CHAT_API_KEY || "",
	STREAM_CHAT_API_SECRET: process.env.STREAM_CHAT_API_SECRET || "",
	OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
	NEXT_PUBLIC_POSTHOG_KEY: process.env.NEXT_PUBLIC_POSTHOG_KEY || "",
	NEXT_PUBLIC_POSTHOG_HOST: process.env.NEXT_PUBLIC_POSTHOG_HOST || "",
};
